BUGFIX: Allow to configure Imagick resource limits
neos/imagine pull request #2
Opened 2017-04-04 09:03 UTC by kitsunet

In order to be able to run in confined server environments a resource
limit for Imagick can be configured now as otherwise Imagick is very
generous in it's resource usage.

2017-04-04 09:04 UTC, kitsunet commented
Seems for styleCI I probably need to change this to psr-2 which apparently was never done...

2017-04-04 09:15 UTC, kdambekalns commented
Ok, StyleCI still fails, but at least it "fails correctly" now :)

2017-04-04 09:20 UTC, kdambekalns approved these changes
Looks good… I guess @robertlemke can actually test it?!

2017-04-07 14:55 UTC, aertmann requested changes

2017-04-07 14:55 UTC, aertmann commented on Classes/TYPO3/Imagine/ImagineFactory.php
>       * @Flow\Inject
this one should get fixed too right? not sure what's going on with the indentation, seems mixed up?

2017-04-07 14:55 UTC, aertmann commented on Configuration/Settings.yaml
> +        # define a map of limits, where the key is an int (one of the "IMagick::RESOURCETYPE_*" constants)
`Imagick::` no?

2017-04-07 14:55 UTC, aertmann commented on Classes/TYPO3/Imagine/ImagineFactory.php
> +		$limits = $this->settings['driverSpecific']['Imagick']['limits'] ?? [];
null coalesce operator only available in PHP 7.0+, Imagine 2.0 requires Flow ~3.0 which is 5.5

2017-04-11 02:23 UTC, aertmann approved these changes
LGTM by reading

2017-04-13 06:48 UTC, kdambekalns approved these changes

2017-04-13 06:48 UTC, merged